1 # This viminfo file was generated by Vim 7.4.
2 # You may edit it if you're careful!
3
4 # Value of 'encoding' when this file was written
5 * encoding = utf - 8
6
7
8 # hlsearch on(H) or off(h) :
    9 ~H
    10 # Last Search Pattern :
11 ~MSle0 / int
12
13 # Last Substitute Search Pattern :
14 ~MSle0~&typdef
15
16 # Last Substitute String :
17 $int
18
19 # Command Line History(newest to oldest) :
    20 : q
    21 : % s / typdef / int
    22 : % s / int / typdef
    23 : wq
    24 : $
    25 : w
    26 : set nu
    27
    28 # Search String History(newest to oldest) :
    29 ? typdef
    30 ? int
    31 ? / int
    32
    33 # Expression History(newest to oldest) :
    34
    35 # Input Line History(newest to oldest) :
    36
    37 # Input Line History(newest to oldest) :
    38
    39 # 寄存器 :
    40 "0      CHAR    0
    41         int mai
    42 ""1     LINE    0
    43         int mai
    44 "2      LINE    0
    45         int main() {
    46 "3      LINE    0
        47         return
        48 "4      LINE    0
        49         printf("hello world!\n");
    50 "5      LINE    0
        51                 return 0;
    52
}
53 "6      LINE    0
54         printf
55 "7      LINE    0
56         int main() {
57                 printf("hello world!\n");
58                 return 0;
59 "8      LINE    0
60                 printf("hello world!\n");
61
62 # 文件标记:
63 '0  3  0  ~/桌面/hello.c
64 '1  65  5  /etc/vimrc
65 '2  1  0  ~/桌面/hello.c
66 '3  7  0  ~/桌面/hello.c
67
68 # 跳转列表(从新到旧) :
    69 - '  3  0  ~/桌面/hello.c
    70 - '  4  1  ~/桌面/hello.c
    71 - '  2  0  ~/桌面/hello.c
    72 - '  1  0  ~/桌面/hello.c
    73 - '  65  5  /etc/vimrc
    74 - '  1  0  /etc/vimrc
    75 - '  7  0  ~/桌面/hello.c
    76 - '  6  0  ~/桌面/hello.c
    77 - '  65  5  /etc/vimrc
    78 - '  1  0  /etc/vimrc
    79
    80 # 文件内的标记历史记录(从新到旧) :
    81
    82 > ~/ 桌面 / hello.c
    83         "       3       0
    84 ^ 4       0
    85         .       3       0
    86 + 1       18
    87 + 2       37
    88 + 7       0
    89 + 7       2
    90 + 7       0
    91 + 7       0
    92 + 2       11
    93 + 7       0
    93, 1 - 8        78 %
